### ISSUE TITLE
Github.io page doesn't work

### ISSUE THREAD

**Issue by thibaultmol** [LuisMayo/GoogleSTTtoSRTConverter#6]
Hi, I recently tried to use the github io page for this project (might setup the google cloud functions main project later, but just wanted to convert some output for now).
But when I open the page I already see an error in the console.

**Comment by LuisMayo** [comment]
I think you are referring to this error:
`Uncaught ReferenceError: exports is not defined
    at convertGSTTToSRT.js:2`
I'll look into it, however the page should work for you anyway, doesn't it work? Or are you talking about any other error?

**Comment by LuisMayo** [comment]
Referred error may be fixed now. Please confirm @thibaultmol or provide more information about the error you're experiencing (when happened, which navigator were you using, etc)
Thanks for your help!

**Comment by thibaultmol** [comment]
It probably works now. I just realized that the script I made to get the text frmo the api doesn't output it the same way. So instead of adjusting my code, I'll just use your script instead.

**Comment by LuisMayo** [comment]
Sure!
I don't know how did you get the output but you may share it(and what did you do to get it) with me via here or my personal email luismayovalbuena at outlook dot es and I'll check if script could be modified to support it

Thanks for your time!
